# Generated by Django 2.2.1 on 2019-07-31 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='composite title')),
                ('text', models.TextField(verbose_name='coposite content')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Problem id')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('score', models.FloatField(verbose_name='score of user on problem')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sentence id')),
                ('sentence', models.TextField(verbose_name='Sentence content')),
                ('length', models.IntegerField(verbose_name='Sentence length')),
                ('similar_sentence', models.TextField(blank=True, verbose_name='Similar sentence')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='User id')),
                ('name', models.CharField(default='anonymous', max_length=20)),
                ('tel_number', models.CharField(max_length=20, verbose_name='User tel number')),
            ],
        ),
        migrations.CreateModel(
            name='GoodAnswer',
            fields=[
                ('record_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ProblemRecord')),
            ],
        ),
        migrations.AddField(
            model_name='problemrecord',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Sentence'),
        ),
        migrations.AddField(
            model_name='problemrecord',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
