# Generated by Django 2.2.1 on 2019-07-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190731_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='length',
        ),
        migrations.AddField(
            model_name='sentence',
            name='sentence_type',
            field=models.IntegerField(choices=[(0, '短'), (1, '中等长度'), (2, '长')], default=0, verbose_name='Sentence type'),
        ),
    ]
