# Generated by Django 2.2.1 on 2019-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190731_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence_type',
            field=models.CharField(choices=[('s', '短'), ('m', '中等长度'), ('l', '长')], max_length=10, verbose_name='Sentence type'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='similar_sentence',
            field=models.TextField(verbose_name='Similar sentence'),
        ),
    ]
