# Generated by Django 2.2.4 on 2019-08-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190731_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
                ('category_id', models.IntegerField(verbose_name='句子相似度1,词汇生僻度2,句子可读性3,句子复杂度4')),
                ('problem_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ProblemRecord')),
            ],
        ),
    ]
