# Generated by Django 2.2.4 on 2019-08-06 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_recorddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemrecord',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='save time'),
        ),
    ]
