# Generated by Django 2.2.1 on 2019-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_problemrecord_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddetail',
            name='info',
            field=models.TextField(blank=True, verbose_name='具体细节'),
        ),
    ]
